version: '3.8'

services:
  courtlistener-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courtlistener-mcp-server
    ports:
      - "8000:8000"
    environment:
      - COURTLISTENER_API_KEY=${COURTLISTENER_API_KEY}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - courtlistener-network

networks:
  courtlistener-network:
    driver: bridge
